gst/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin


from .views import home_page, about_page, contact_page, login_page, register_page

urlpatterns = [
    url(r'^$', home_page),
    url(r'^about/$', about_page),
    url(r'^contact/$', contact_page),
    url(r'^login/$', login_page),
    url(r'^register/$', register_page),
    url(r'^products/', include("products.urls", namespace="products")),
    url(r'^receipt/', include("receipt.urls", namespace="receipt")),
    url(r'^admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

receipt/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include

from .views import  CreateItemReceipt, UpdateUserReceipt, CreateUserReceipt
from .views import PrintReceipt

urlpatterns = [
    url(r'^item-receipt/(?P<pk>\d+)/$', CreateItemReceipt.as_view(), name='item-receipt'),
    url(r'^user-receipt/$', CreateUserReceipt.as_view(), name='user-recipt'),
    url(r'^update-user-receipt/(?P<pk>\d+)/$', UpdateUserReceipt.as_view(), name='update-user-receipt'),
    url(r'^print-receipt/$', PrintReceipt.as_view(), name='print-receipt'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

receipt/models.py
from django.db import models
from products.models import Product
from gst.utils import unique_order_id_generator
from django.db.models.signals import pre_save

class ItemReceipt(models.Model):
   order_id = models.CharField(max_length=500)
   item     = models.ForeignKey(Product, blank=True,null=True)
   item_no  = models.IntegerField(default=0)
   new      = models.BooleanField(default=True)

   def __str__(self):
       return str(self.order_id)

class UserReceipt(models.Model):
    name        = models.CharField(max_length=60)
    order_id    = models.CharField(max_length=500)
    total_items = models.IntegerField(default=0)
    sub_total   = models.DecimalField(decimal_places=2,max_digits=10,default=0.00)
    date_time   = models.DateTimeField(auto_now_add=True)
    orders      = models.ManyToManyField(ItemReceipt)
    billed      = models.BooleanField(default=False)

    def __str__(self):
        return str(self.order_id)



def pre_save_create_order_id(sender, instance, *args, **kwargs):
    if not instance.order_id:
       instance.order_id = unique_order_id_generator(instance)

pre_save.connect(pre_save_create_order_id, sender=UserReceipt)

receipt/views.py
from django.shortcuts import render
from .models import UserReceipt, ItemReceipt
from django.shortcuts import redirect
from products.models import Product
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView


class CreateUserReceipt(CreateView):
    model = UserReceipt
    template_name = 'receipt/receipt_form.html'
    fields = ['name']
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.save()
        ItemReceipt.objects.create(order_id=obj.order_id)
        obj1 = ItemReceipt.objects.get(order_id=obj.order_id, new=True)
        return redirect(reverse('receipt:item-receipt', kwargs={'pk': obj1.id}))
    # success_url = reverse_lazy('receipt:item-receipt')

class CreateItemReceipt(UpdateView):
    model = ItemReceipt
    template_name = 'receipt/itemreceipt_form.html'
    fields = ['item_no']

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.new = False
        obj.save()
        obj1 = UserReceipt.objects.get(order_id=obj.order_id)
        return redirect(reverse('receipt:update-user-receipt', kwargs={'pk': obj1.id}))
    #success_url = reverse_lazy('receipt:update-user-receipt')

class UpdateUserReceipt(UpdateView):
    model = UserReceipt
    template_name = 'receipt/receipt_form.html'
    fields = []
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.save()
        ItemReceipt.objects.create(order_id=obj.order_id)
        obj1 = ItemReceipt.objects.get(order_id=obj.order_id, new=True)
        return redirect(reverse('receipt:item-receipt', kwargs={'pk': obj1.id}))

    # success_url = reverse_lazy('receipt:item-receipt')
class PrintReceipt(ListView):
        template_name = 'receipt/print_receipt.html'
        def get_queryset(self):
            if (UserReceipt.objects.filter(billed=False)):
                obj = UserReceipt.objects.get(billed=False)
                obj1 = UserReceipt.objects.get(billed=False)
                obj.billed = True
                obj.save()

            if(UserReceipt.objects.filter(order_id=obj1.order_id)):
                return UserReceipt.objects.get(order_id=obj1.order_id)
            else:
                return UserReceipt.objects.all()

receipt/templates/receipt/itemreceipt_form.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
    <form action="" method="post">{% csrf_token %}
    <div class="col">Item No: {{ form.item_no }}<br/></div><div>
<br/>
<br/>

             <button type="submit" class="btn btn-primary"> Submit </button>
</form>
    </div>

{% endblock %}

receipt/templates/receipt/print_receipt.html
{% extends 'base.html' %}
{% url 'student-register:detail' as student_url %}
{% block content %}
<div class="row">
    <div class="col"><h1>BILL</h1><hr/><br/></div>
</div>
<div class="row"><div class="col-5 ">{{ object_list.name }}
</div></div>

    <table class="table">
  <thead>
    <tr>
      <th scope="col">S No.</th>
      <th scope="col">Item</th>
{#      <th scope="col">Order No.</th>#}
      <th scope="col">Price</th>
{#      <th scope="col">Year</th>#}
{#      <th scope="col">Books issued</th>#}
{#      <th scope="col">Total Books Issued</th>#}
    </tr>
  </thead>
  <tbody>
    </tbody>
</table>{% endblock %}

receipt/templates/receipt/receipt_form.html
{% extends 'base.html' %}
{% block content %}
    <div class="row"><div class="col">
        <h1>Receipt</h1>
    </div></div>
    <div class="row"><div class="col">
Customer Name: {{ object.name }}

    </div>
    <div class="col">
Order Id: {{ object.order_id }}

    </div></div>
    <div class="row"><div class="col">
Total Items: {{ object.total_items }}

    </div>
    <div class="col">
Subtotal : Rs{{ object.sub_total }}

    </div></div>

    <div class="row"><div class="col">
        <hr/><br/>
    </div></div>
    <div class="row">
    <form action="" method="post">{% csrf_token %}
    <div class="col">{% if object.name is None %}Name {{ form.name }}<br/></div><div>{% endif %}
<br/>
<br/>

             <button type="submit" class="btn btn-primary"> Submit </button>
<br/>
    </form>
<div class="row"><div class="col">
        <br/><hr/>
    </div></div>

    </div>
<br/>

    <div class="row"><div class="col">
        <a href="{% url 'receipt:print-receipt' %}" class="btn btn-success">Print</a>
    </div></div>

{% endblock %}